# This is a Docker Compose configuration
# intended for development purposes only

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      APP_URL: http://localhost:${DEV_PORT:-8080}
    ports:
      - ${DEV_PORT:-8080}:80
    volumes:
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: /app/docker/entrypoint.app.sh
  node:
    image: node:alpine
    working_dir: /app
    user: node
    volumes:
      - ./:/app
    entrypoint: /app/docker/entrypoint.node.sh
#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - ${DEV_MAIL_PORT:-8025}:8025
